### ISSUE TITLE
Kite tries to double start on system startup

### ISSUE THREAD

**Issue by its-dhung** [kiteco/issue-tracker#197]
> I am getting error popup box while starting my computer stating that Kite was unable to listen on port 46624. I have attached a screenshot of it. I tried reinstalling it, checking port but no luck. Please let me know if you have any solution.

Another user wrote in saying that he does not have multiple user accounts logged in at the same time.

I have also seen this problem when my computer wakes from sleep also. What is causing Kite to double start?

**Comment by adamsmith** [comment]
My guess is there's a plugin trying to reach Kite on port 46624 but it's momentarily not able to because the machine is waking from sleep or something.

To confirm this, maybe it'd be useful to know the command line arguments provided when Kite was starting — that could tell us what was starting kited. If we think that's a good idea, we could add it to the message and also add text asking the user to email support@kite.com about it?

(Another option would be to not show this message, and just quit instead.)

(cc @metalogical)

**Comment by metalogical** [comment]
I'm in favor of not showing the message and just quitting. Are there any cases where this message pops up and it indicates a real issue the user would need to email us about?

**Comment by adamsmith** [comment]
On Windows machines where multiple users are logged in there is an issue where user A is talking to kited running under user B's account.

User A would see this message. If we remove the message you still get the same net effect, just less of an indication of a problem.

Maybe one approach would be to remove this message and then create a GH issue to track this cross-user scenario.

**Comment by stefansimik** [comment]
Same problem here.

![2020-05-22_114503](https://user-images.githubusercontent.com/6208056/82654921-b3a4d780-9c21-11ea-9ec4-3d167cba90b6.png)

**Comment by its-dhung** [comment]
Let's go ahead and stop showing this error message and quit the duplicate instance. Pretty easy fix that will stop this annoying issue that multiple users have written in about.

**Comment by adam-grant-hendry** [comment]
Same problem

![kite_error](https://user-images.githubusercontent.com/59346180/90279803-b4af6480-de1e-11ea-9547-47ae15d02111.png)

**Comment by jansorg** [comment]
The fix for this is contained in the latest release now.
