### ISSUE TITLE
Detect VSCodium in Kite plugin manager

### ISSUE THREAD

**Issue by ChaosOrdeal** [kiteco/issue-tracker#224]
You should support VSCodium, mostly because it will require almost no effort.  VSCodium is a fork of VSCode that endeavors to be identical to VSCode in almost every way.  All you would need to do is detect that it's running (different .exe name) and treat it identically to VSCode, otherwise.

**Comment by metalogical** [comment]
Hi @ChaosOrdeal 

I'm not very familiar with VSCodium, but it looks like it integrates with the regular VS Code marketplace? If so, you should be able to install the Kite extension for VS Code directly without going through Kite's plugin manager.

Please let us know if this works for you.

**Comment by ChaosOrdeal** [comment]
It does, but it never detects that VSCode is running (because it isn't).  Does your client look for a particular .exe?

**Comment by metalogical** [comment]
I think you misunderstand me. Kite does not need to detect that VS Code is running in order to function. All you need are:

- the Kite engine installed
- the Kite for VS Code extension installed

The Kite for VS Code extension can be installed via the VS Code extension marketplace directly, without going through the Kite app.

**Comment by metalogical** [comment]
What functionality appears missing to you?

**Comment by metryy** [comment]
I think @ChaosOrdeal wants the Kite program to detect VSCodium as VSCode in the actual program automatically like it does with the official IDE programs, or atleast I do since Kite runs in the background 24/7 it'd be nice for it to provide a little bit more convenience like it does with the official IDEs as I use VSCodium as my main IDE.

**Comment by ent3r** [comment]
I don't think this would be too difficult to make. The only differences between VSCode and VSCodium is that VSCodium installs itself in a different folder. 

- VSCodium installation folder: `C:\Program Files\VSCodium`
- VSCodium user folder: `C:\Users\%username%\.vscode-oss`

**Comment by axeII** [comment]
@metalogical 
>Microsoft’s vscode source code is open source (MIT-licensed), but the product available for download (Visual Studio Code) is licensed under this not-FLOSS license and **contains telemetry/tracking**. 


Source: https://vscodium.com

Devs can we have please an official support for VSCodium :pray:?

**Comment by metalogical** [comment]
To clarify again, in case it was unclear:

You *can* currently use Kite with VSCodium, by installing the Kite extension from the VS Code marketplace (https://marketplace.visualstudio.com/items?itemName=kiteco.kite).

The only piece that is missing is support within Kite for automatically detecting VSCodium and installing the extension for you. But this is *not* necessary for Kite to function.

**Comment by axeII** [comment]
@metalogical Thanks for that link. 

Problem I had was that I could not find kite in VSCodium market place which is https://open-vsx.org. Because of this I was not able to easily install plugin for VSCodium (I though it's not possible for a moment).

However I was able to manually **install** kite package by downloading  `.vsix` file and then installing extension using this file ([like this](https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually)).

**Btw** it would be great to have plugin in open-vsx but due license it' not possible to be done by community.

**Comment by tywmick** [comment]
There's currently no legal way to install and use Kite's VS Code plugin with VSCodium, as far as I can tell.

1. Visual Studio Marketplace's [Terms of Use](https://aka.ms/vsmarketplace-ToU) requires that the Marketplace and any extensions it distributes only be used with Microsoft products. This seems to rule out both of the following:
    - [Connecting VSCodium to VS Marketplace](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace) (though one VS Code maintainer at Microsoft [thinks it's fine](https://github.com/Microsoft/vscode/issues/1557#issuecomment-173449135))
    - Downloading the `.vsix` directly from [the VS Marketplace website](https://marketplace.visualstudio.com/items?itemName=kiteco.kite) and installing it manually
2. The [license](https://github.com/kiteco/vscode-plugin/blob/master/LICENSE) of Kite's VS Code plugin requires obtaining written permission before reproducing it, so that seems to rule out cloning the repository and building it yourself.

Not that I think doing any of those things is _wrong_, per se, just not _legal_. All else being equal, legal would be nicer. [Publishing to Open VSX](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) or adding the compiled `.vsix` to the plugin's [GitHub Releases](https://github.com/kiteco/vscode-plugin/releases) would fix that.

**Comment by metalogical** [comment]
@tywmick thanks, I wasn't aware of the VS Marketplace ToU. Seems like we should just publish to Open VSX.
