### ISSUE TITLE
Copilot not running on Debian 10

### ISSUE THREAD

**Issue by its-dhung** [kiteco/issue-tracker#233]
System details:

![image](https://user-images.githubusercontent.com/3752225/82263290-6a017780-9917-11ea-84ee-528e16288e1e.png)

kited seems to be running but the Copilot doesn't start.

**Comment by eliotb** [comment]
Given that this is a fairly sparse report, I'm going to add my report here. (Also using Debian 10)

Originally submitted via feedback form, but Daniel said I should raise a github issue.

It took me a while to figure out what "the kite application" is.
Because I installed via spyder (running that from a venv), it was pretty opaque as to what was
installed where...
/home/eliot/.local/share/kite/current/linux-unpacked/kite
[10851:0502/132314.321242:FATAL:setuid_sandbox_host.cc(157)] The SUID
sandbox helper binary was found, but is not configured correctly. Rather
than run without sandboxing I'm aborting now. You need to make sure that
/home/eliot/.local/share/kite/kite-v2.20200423.1/linux-unpacked/chrome-sandbox
is owned by root and has mode 4755.
Trace/breakpoint trap

I'm assuming it is this (and there is a problem running it).

```
/home/eliot/.local/share/kite/current/linux-unpacked/kite
[10851:0502/132314.321242:FATAL:setuid_sandbox_host.cc(157)] The SUID
sandbox helper binary was found, but is not configured correctly. Rather
than run without sandboxing I'm aborting now. You need to make sure that
/home/eliot/.local/share/kite/kite-v2.20200423.1/linux-unpacked/chrome-sandbox
is owned by root and has mode 4755.
Trace/breakpoint trap
```

Same basic message when invoking the kite://home from a browser.

BTW I can see that kited is running. The kite intro inside spyder worked
fine.

I'm not sure why kite expects to be installed in root owned directory when it is installed by a  normal user?!

**Comment by ChrisiCarr** [comment]
I have been asked to add my report here via kite support.

I am unable to launch Kite using Debian. 
Log found in /var/log/messages > "May 24 01:50:45 kernel: [2137.487858] traps: kite[4843] trap int3 ip:5634bafdb633 sp:7fff206b7220 error:0 in kite[5634b915d000+53d8000]"

Sys info:

Distributor ID: Debian
Description: Debian GNU/Linux 10 (buster)
Release: 10
Codename: buster

**Comment by jansorg** [comment]
I can confirm that this happens on a fresh installation of Debian 10. 
The cause is explained at https://github.com/electron/electron/issues/17972
We'll investigate about the best way to fix this for Kite
