### ISSUE TITLE
Copilot Window

### ISSUE THREAD

**Issue by Mistobaan** [kiteco/issue-tracker#255]
- [ ] The Copilot window has some weird width restrain that does not allow me to set it to 1/3 of the window. See picture:
- [ ] There is no way to increase the font size as far as I know. 
- [ ] As a User I would like to "click to add" on the "how others are using it" suggestion list. It would be nice to just click on that and add it to my current code window.
- [ ] As a user I would like to have the list of my relevant snippets appear under the "how others are using it" 
![image](https://user-images.githubusercontent.com/112599/83992059-d31b5000-a903-11ea-8f7e-16c5f7d1f413.png)

- Which snippets engine are you using overall?
- Why do you need to scan the WHOLE Computer for a PYTHONPATH??? I have 20TB of disks...

**Comment by its-dhung** [comment]
> The Copilot window has some weird width restrain that does not allow me to set it to 1/3 of the window.

This is by design, unfortunately. The Copilot was intended to be a quick reference tool as opposed to a full-fledged documentation tool (i.e. the browser), so it was designed to take up minimal screen width. 

>  There is no way to increase the font size as far as I know.

You should be able to use `ctrl` + `=` to increase the font size. `ctrl` + `-` will decrease the font size.

> Which snippets engine are you using overall?

If you're talking about how we provide snippets in the editor, we use the editor's native snippets API.

> Why do you need to scan the WHOLE Computer for a PYTHONPATH??? I have 20TB of disks...

We admittedly didn't design the indexing logic with this use case (10+ TB disk space) in mind, but this is a good point. We may make changes to how this works depending on what other users are experiencing.

>  As a User I would like to "click to add" on the "how others are using it" suggestion list. It would be nice to just click on that and add it to my current code window.

>  As a user I would like to have the list of my relevant snippets appear under the "how others are using it"

These are both good feature requests. Feel free to open a separate feature request issue so that we can track it!
