### ISSUE TITLE
Kite editor plugin not loading up in Jupyterlab v2.2.4

### ISSUE THREAD

**Issue by djwight** [kiteco/issue-tracker#346]
Hey all,
I followed the instructions for installation of the jupyter lab extension of Kite but despite it being installed and enabled it doesn't load up in jupyter lab. 
I tried to uninstall the extension in jupyter lab and reinstall it but the problem remains.

Below is the info requested for the issue but let me know if you need/want more info.

Thanks,
Darren

**OS:** Ubuntu 18.04

**Kite desktop installed:** Yes

**Error on Installation:** No error shown

**Output of** `pip list` - attached as `.txt`

**Output of** `jupyter labextension list`:
![Screenshot from 2020-08-13 14-24-24](https://user-images.githubusercontent.com/51029384/90134961-3b5a3800-dd72-11ea-8cc9-d0a3b2026e6b.png)

[piplist.txt](https://github.com/kiteco/issue-tracker/files/5069016/piplist.txt)

**Comment by djwight** [comment]
Additionally, it is different from [#333](https://github.com/kiteco/issue-tracker/issues/333) as I don't see kite in the status bar at all (bottom left, should be next to the python kernel).

![Screenshot from 2020-08-13 14-47-36](https://user-images.githubusercontent.com/51029384/90136378-634a9b00-dd74-11ea-9722-3df7245a13a2.png)

**Comment by its-dhung** [comment]
It looks like JupyterLab thinks the Kite plugin is both installed and uninstalled. You may need to manually change your `build_config.json` for this to work. [This thread](https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688) may be relevant for you.

**Comment by djwight** [comment]
Hey @its-dhung,

Thanks for the response but following the thread failed to resolve the issue. 
Modifyied the `build_config.json` in the following dir for my current conda env `/.../anaconda3/envs/myenv/share/jupyter/lab/`. In this file I removed the `uninstalled` info relating to kite but with no success.

`labextensions` show it is **installed** and **enabled**:
![Screenshot from 2020-08-20 14-54-25](https://user-images.githubusercontent.com/51029384/90773223-e2504e00-e2f5-11ea-8bc0-f59c738d3e03.png)

Do you have any other ideas how I could resolve this issue?

**Comment by its-dhung** [comment]
A handful of questions:

1. To confirm, you also ran `jupyter lab build` after changing your `build_config.json`?
2. What happens if you uninstall and reinstall the plugin via `jupyter labextension uninstall @kiteco/jupyterlab-kite` and then `jupyter labextension install @kiteco/jupyterlab-kite`.
3. Do you happen to have multiple kernels installed or are you using a remote/containerized instance of JupyterLab? Kite won't work in these environments.

If none of the above is helpful, can you try the following:

1. Restart Kite.
2. Restart JupyterLab.
3. Share the contents of your browser's JavaScript console (in the tab where JupyterLab is running) and also please [generate your logs](https://help.kite.com/article/96-contact-us-with-logs) from Kite's Copilot and share them in this issue.

**Comment by djwight** [comment]
Hey @its-dhung,
Thanks again for the information.
I can confirm that I ran `jupyter lab build` after changing the config.

**Good news**- Randomly (but happily) my jupyter lab plugin is now working. I am not sure what the fix was, I have the kite pro free trial but don't think that was it (if it reverts after the trial, I will add to this thread).
 
It's still not identified in the Kite app's Plugins tab, but this is perhaps not a big issue since the plugin works in jupyter.
