### ISSUE TITLE
Kite was unable to listen on port 46624

### ISSUE THREAD

**Issue by njNafir** [kiteco/issue-tracker#448]
When I turn on my windows 10 pc. I got a confirmation message box from kite engine, And that is -> Kite was unable to listen on port 46624. This usually means another instance of kite is already running, ............., Kite will now exit.

![Kite was unable to listen on port 46624](https://user-images.githubusercontent.com/50158541/97258353-754fbc00-1842-11eb-80ef-203eadfdc4b6.png)

**Comment by its-dhung** [comment]
Can you check and see if Kite is running after you receive that message? If it is, what version of Kite are you using?

**Comment by njNafir** [comment]
Kite is running after you receive that message. But I don't know exactly how to find the version of kite!
The popup appears today also.

**Comment by its-dhung** [comment]
@metalogical didn't we implement a fix for this dialog to not show up on Windows if a previous instance of Kite was running?

**Comment by njNafir** [comment]
Is kite is doing wrong ? like trying to run multiple time?

**Comment by its-dhung** [comment]
That's quite an old version of Kite. Our Windows auto updater has some known issues, so the easiest way for you to update Kite is to uninstall Kite, and then download it and install it again from https://kite.com/download. This issue should be fixed in the latest version of Kite. Please re-open this issue if that isn't the case for you.
