### ISSUE TITLE
Unable to install Kite for VS Code

### ISSUE THREAD

**Issue by gellasangameshgupta** [kiteco/issue-tracker#702]
I have installed Kite a long back (Pro User) and installed it to different editors. They are working fine, and I took some break from coding. I recently installed the kite for VS Code, and it is not installing and unable to find the issue. I pasted the image below. Please give me a solution as soon as possible.
![image](https://user-images.githubusercontent.com/66055716/111813487-46280d00-88ff-11eb-802b-67d20ee135b2.png)

**Comment by poteat** [comment]
The underlying error is saying that VS Code is not installed. I would suggest to try reinstalling VS Code, or either manually updating your PATH.

**Comment by gellasangameshgupta** [comment]
I tried reinstalling many times, but still, that error is popping up. Can you please tell me how to update the path?

**Comment by edzkite** [comment]
On Windows, VS Code should automatically be added to the path. See Microsoft's [documentation](https://code.visualstudio.com/docs/setup/windows#_installation). Re-installing VS Code may help here, otherwise you can do so [manually](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/). 

Alternatively, instead of installing the plugin via the Kite desktop application, you can install it directly from the VS Code marketplace, just like any other extension.

**Comment by gamer69909** [comment]
i could not found the kite extension
